- hosts: control, compute
  become: true

  tasks:
     - name: replace hosts entry to prevent duplicate entries
       lineinfile:
          path: /etc/hosts
          regexp: '^10\.(0|1)\.0\..*'
          firstmatch: yes
          backup: yes
          line: "#"
          backrefs: yes
