apiVersion: apps/v1
kind: Deployment
metadata:
   name: scheduler-service
   labels:
      app: scheduler
spec:
   replicas: 1
   selector:
      matchLabels:
         app: scheduler
   template:
      metadata:
         labels:
            app: scheduler
      spec:
         serviceAccountName: scheduler-sa
         containers:
            - name: scheduler-container
              image: ashiven/scheduler:1.2
              env:
                 - name: SCHEDULING_PERIOD
                   value: "10"
                 - name: CARBON_AWARE
                   value: "true"
