apiVersion: v1
kind: ServiceAccount
metadata:
   name: scheduler-sa
   namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
   namespace: default
   name: scheduler-role
rules:
   - apiGroups: [""]
     resources: [pods]
     verbs: [get, list, create, delete]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
   name: scheduler-rolebinding
   namespace: default
roleRef:
   apiGroup: rbac.authorization.k8s.io
   kind: Role
   name: scheduler-role
subjects:
   - kind: ServiceAccount
     name: scheduler-sa
