apiVersion: v1
kind: ServiceAccount
metadata:
   name: scheduler-sa
   namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
   name: scheduler-role-cluster
rules:
   # Framework: knowing which other operators are running (i.e. peering).
   - apiGroups: [kopf.dev]
     resources: [clusterkopfpeerings]
     verbs: [list, watch, patch, get]

   # Framework: runtime observation of namespaces & CRDs (addition/deletion).
   - apiGroups: [apiextensions.k8s.io]
     resources: [customresourcedefinitions]
     verbs: [list, watch]
   - apiGroups: [""]
     resources: [namespaces]
     verbs: [list, watch]

   # Framework: admission webhook configuration management.
   - apiGroups:
        [admissionregistration.k8s.io/v1, admissionregistration.k8s.io/v1beta1]
     resources: [validatingwebhookconfigurations, mutatingwebhookconfigurations]
     verbs: [create, patch]

   - apiGroups: [""]
     resources: [pods]
     verbs: [get, list, create, delete, watch, patch]

   - apiGroups: [""]
     resources: ["events"]
     verbs: ["create", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
   name: scheduler-rolebinding-cluster
roleRef:
   apiGroup: rbac.authorization.k8s.io
   kind: ClusterRole
   name: scheduler-role-cluster
subjects:
   - kind: ServiceAccount
     name: scheduler-sa
     namespace: default
