apiVersion: v1
kind: Pod
metadata:
   name: workload-placeholder
   labels:
      app: workload-placeholder
spec:
   affinity:
      nodeAffinity:
         requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
               - matchExpressions:
                    - key: kubernetes.io/hostname
                      operator: In
                      values:
                         - placeholder-node
   containers:
      - name: sysbench
        image: zyclonite/sysbench
        command:
           - "/bin/sh"
           - "-c"
           - "placeholder-command"
        imagePullPolicy: IfNotPresent
   restartPolicy: Never
