apiVersion: v1
kind: Pod
metadata:
   name: workload-simulator
   labels:
      app: workload-simulator
spec:
   containers:
      - name: sysbench
        image: zyclonite/sysbench
        command:
           - "/bin/sh"
           - "-c"
           - "sysbench cpu --cpu-max-prime=10000 --time=60 run"
        resources:
           requests:
              cpu: "500m"
              memory: "256Mi"
           limits:
              cpu: "1000m"
              memory: "512Mi"
        imagePullPolicy: IfNotPresent
   restartPolicy: Never
