all:
   hosts:
      k8s-node-1:
         ansible_host: 34.32.54.240
         ip: 10.214.0.8
         access_ip: 34.32.54.240
      k8s-node-2:
         ansible_host: 34.32.40.155
         ip: 10.214.0.9
         access_ip: 34.32.40.155
      k8s-node-3:
         ansible_host: 34.32.69.183
         ip: 10.214.0.10
         access_ip: 34.32.69.183
   children:
      kube_control_plane:
         hosts:
            k8s-node-1:
            k8s-node-2:
            k8s-node-3:
      kube_node:
         hosts:
            k8s-node-1:
            k8s-node-2:
            k8s-node-3:
      etcd:
         hosts:
            k8s-node-1:
            k8s-node-2:
            k8s-node-3:
      k8s_cluster:
         children:
            kube_control_plane:
            kube_node:
      calico_rr:
         hosts: {}
